### ISSUE TITLE
apply some license

### ISSUE THREAD

**Issue by Romex91** [peirick/Tesseract-OCR_for_Windows#1]
I'd like to use the repository, but I'm concerned by licensing paranoia.
Could you please apply some permissive software license to the repository?
Thanks

**Comment by peirick** [comment]
This projekt consists of an assembling of other existing projects. Every sub project has it's own license. Do you know what's best practise in such a situation?

**Comment by peirick** [comment]
I've added an LICENSE.md file MIT

**Comment by Romex91** [comment]
I think that's enough, since there is a license file for each sub project.
All the licenses are copyfree so they sholdn't affect the final distribution license.
Thank you.
