### ISSUE TITLE
Help : vs2015 warn me that debug/zlib.lib is not a valid win32 program and stop running while building (F7) is totally ok

### ISSUE THREAD

**Issue by liujunvii** [peirick/Tesseract-OCR_for_Windows#12]
Hi,  i got an issue during running tesseract without debugging (ctrl+F5) in vs2015. vs2015 warn me that debug/zlib.lib is not a valid win32 program and just stop running while building (F7) is totally ok and pass. 

I downloaded the "VS2015_Tesseract-master.zip", released the file, run build_tesseract.bat through git cmd, and run the tesseract.sln with vs2015.  Did i miss somthing? I have no clue about how to solve this problem.Plz help & really thanx a lot!

**Comment by liujunvii** [comment]
The issue have been solved &  the project works great! thanx

**Comment by varun1994varun** [comment]
Hi liujunvii,
I also have the same issue.
Can you tell me how did you solve it?
Thanks!

**Comment by liujunvii** [comment]
Hi,peirick. Just modify the priority running program to tesseract. It seems
that the default priority running one is zlib.lib. I solve the problem by
this way. Try it and wish good luck!
