### ISSUE TITLE
build_tesseract.bat run error (Errorlevel: 128)

### ISSUE THREAD

**Issue by ahmed-tea** [peirick/Tesseract-OCR_for_Windows#19]
when i run build_tesseract.bat i get
fatal: Not a git repository (or any of the parent directories): .git
"Program failed, please check this log file for errors ..."
Errorlevel: 128

**Comment by peirick** [comment]
Did you correctly clone this repository with git?

**Comment by ahmed-tea** [comment]
I downloaded it as zip file and executed the build_tesseract.bat

**Comment by peirick** [comment]
Well that does not work. You need to check it out with git, because Tesseract and leptonica source is loaded with git as external module in  build.bat.
