### ISSUE TITLE
VS Express for Desktop

### ISSUE THREAD

**Issue by seanpoulter** [peirick/Tesseract-OCR_for_Windows#2]
First, thanks for putting all this together!

I had an issue building that I wanted to clarify for anyone else using Visual Studio Express 2015 for Desktop. The output from **liblept.sln** is **liblept.lib** instead of **leptonica.lib** so both .bat files fail. Have you encountered this? We could add a note to the README or update the Project files appropriately.

**Comment by peirick** [comment]
Thank you for reporting!
I recently renamed it, and missed to correct the projects. I will fix this soon.

**Comment by peirick** [comment]
Is fixed now.
