### ISSUE TITLE
can your branch be merged into the github leptonica master?

### ISSUE THREAD

**Issue by DanBloomberg** [peirick/Tesseract-OCR_for_Windows#3]
Tobias,

The official master for leptonica is now at: github.com/danbloomberg/leptonica

We put it up there in January.  As you can imagine, the maintenance and development is much easier than when it was on code.google.com (and only updated with a release every 5 months or so).  I particularly like the automatic appveyor windows builds, because I previously had to rely on others to test the code on windows.

I'd rather not have forks if they are not necessary, because they are not efficient and generally cause confusion.  Would you like to have responsibility for keeping the master up to date with VS?

  -- Dan

**Comment by peirick** [comment]
Hello Dan,

yes of course i would like to do that. I feel honored to help. It's always good not to duplicate work. How should the work be coordinated? I'm relativly new on github.

Kind regards

Tobias

**Comment by DanBloomberg** [comment]
Tobias,

Great.  I'm also very new to github (know only the most simple operations),
and in addition I've always relied on others for help on the MS side, both
with the MS libraries and the VS builds.

With cmake on github, the builds are tested for windows with appveyor on
each push, and I assume this works for some set of VSC++ versions.  My
general philosophy has been to keep leptonica versatile, as long as it
didn't get complicated.  For example, I wouldn't want windows users to be
restricted to VS2015.  On the other hand, support for very old versions
shouldn't be indefinite.  Perhaps passing appveyor is a good compromise?
 (I'm just guessing)

What can you do?  Perhaps check out the current from head and fill in
features, simplifications (e.g., snprintf doesn't need to be renamed for
VS2015 -- I saw that you did that, and someone submitted that fix two weeks
ago), etc.  -- _whatever you think improves the windows build_.

Or, ... suggestions.

  -- Dan
