### ISSUE TITLE
  tesseractmain.cpp c1xx : fatal error C1083: Cannot open source file: '..\tesseract_3.04\api\tesseractmain.cpp': No such file or directory

### ISSUE THREAD

**Issue by LeaderMalang** [peirick/Tesseract-OCR_for_Windows#5]
tesseractmain.cpp
c1xx : fatal error C1083: Cannot open source file: '..\tesseract_3.04\api\tesseractmain.cpp': No such file or directory.I have download as it is but while i tried to run it on visual studio 2015 i got error . I m using windows 10 . thanks in advance .

**Comment by peirick** [comment]
Try downloading the submodules "git submodule update --init --recursive"

**Comment by peirick** [comment]
@LeaderMalang Did this help?

**Comment by LeaderMalang** [comment]
sorry for late reply Sir . Please can you give me complete guide line about the configuration of tesseract. Now i am facing libtesseract302d.dll missing Error .I do understand that i didn't configured the library incorrectly. Thanks

**Comment by LeaderMalang** [comment]
zlib.dll is not valid win32 application tesseract  . now i have got new error .

I had cloned this git repository then i run the  build_tesseract.bat .After that i have build the whole application tried to debug it . Then i got error zlib.dll is not valid win32 application. 

thanks for your time
