### ISSUE TITLE
zlib.dll is not valid win32 application

### ISSUE THREAD

**Issue by LeaderMalang** [peirick/Tesseract-OCR_for_Windows#7]
zlib.dll is not valid win32 application tesseract . now i have got new error .

I had cloned this git repository then i run the build_tesseract.bat .After that i have build the whole application tried to debug it . Then i got error zlib.dll is not valid win32 application.

thanks for your time

**Comment by peirick** [comment]
You have to activate the Tesseract Project for startup.

**Comment by LeaderMalang** [comment]
what mean to activate the project .Sorry i am beginner with visual studio and tesseract.

**Comment by LeaderMalang** [comment]
thanks its working quite fine .
