### ISSUE TITLE
How i can use ocr command or code to extract text from image using tesseractmain.cpp

### ISSUE THREAD

**Issue by LeaderMalang** [peirick/Tesseract-OCR_for_Windows#9]
I need little help about usage of tesseract .I am not able to understand that how can i extract text from image using tesseractmain.cpp.I successfully Build the source code .But right stuck at how i can use it to perform basic function of ocr. Or how i can add some kind of wrapper for it .Thanks

**Comment by peirick** [comment]
Pleas ask direct in tesseract forum
